### PR TITLE
fix: Remove unnecessary printf

### PR DESCRIPTION
**Pull request by HowJMay**

### CODE REVIEW

**Comment by jserv** [comment]
CI failed because of gcc compilation on Armv7-A target:
> error: 'vld1q_u8_x4' was not declared in this scope; did you mean 'vld1q_u64'?

See https://lore.kernel.org/linux-crypto/20190819141500.1070-1-ard.biesheuvel@linaro.org/
> GCC does not implement the vld1q_u8_x4() intrinsic

**Comment by HowJMay** [comment]
> CI failed because of gcc compilation on Armv7-A target:
> 
> > error: 'vld1q_u8_x4' was not declared in this scope; did you mean 'vld1q_u64'?
> 
> See https://lore.kernel.org/linux-crypto/20190819141500.1070-1-ard.biesheuvel@linaro.org/
> 
> > GCC does not implement the vld1q_u8_x4() intrinsic

Should we wait for the new version of gcc or?

**Comment by jserv** [comment]
> Should we wait for the new version of gcc or?

No, let's create a new pull request to resolve gcc issues.

**Comment by marktwtn** [comment]
I wonder why the CI did not fail before.

**Comment by HowJMay** [comment]
I think the error is not caused by gcc, since `vld1q_u8_x4()` was added in gcc-10.3.

see: https://github.com/gcc-mirror/gcc/commit/391625888d4d97f9016ab9ac04acc55d81f0c26f

**Comment by marktwtn** [comment]
> I think the error is not caused by gcc, since `vld1q_u8_x4()` was added in gcc-10.3.
> 
> see: [gcc-mirror/gcc@3916258](https://github.com/gcc-mirror/gcc/commit/391625888d4d97f9016ab9ac04acc55d81f0c26f)

However, it is added for `aarch64`.
The `arm` architecture is not included.

**Comment by marktwtn** [comment]
The CI failure is caused by the `GCC` version.
In the previous success CI, the `GCC` version for `armv7` is 10.1
However, the failed CI uses the version 10.3.

The `sse2neon.h` has the macros for detecting `GCC` version.
Nonetheless, it does not take care of the version which is greater than 10.1 well.

I will make another pull request to take care of the `GCC` version with different CPU architecture.

**Comment by marktwtn** [comment]
Please rebase to the newest master branch.
The CI problem has been solved.

**Review by marktwtn — APPROVED** [review]

**Pull request merged**
