### PR TITLE
Allow to specify -DSSE2NEON_SUPPRESS_WARNINGS to avoid the #warning about optimization issues

### PR DESCRIPTION
**Pull request by rouault**
This warning breaks builds of applications using -Werror.

### CODE REVIEW

**Review by jserv — CHANGES_REQUESTED** [review]
Mention `SSE2NEON_SUPPRESS_WARNINGS` in top-level `README.md`.

**Comment by rouault** [comment]
> Mention `SSE2NEON_SUPPRESS_WARNINGS` in top-level `README.md`.

done

**Comment by howjmay** [comment]
I think instead of how `SSE2NEON_SUPPRESS_WARNINGS` affect the compilation when optimizations are enabled, we should mention `SSE2NEON_SUPPRESS_WARNINGS` in `Compile-time Configurations` section. Add a new item `SSE2NEON_SUPPRESS_WARNINGS` and describe the usage of it. 
Thank you

**Comment by rouault** [comment]
> Add a new item `SSE2NEON_SUPPRESS_WARNINGS` and describe the usage of it.

done

**Comment by jserv** [comment]
Thank @rouault for contributing!

**Comment by rouault** [comment]
> Thank @rouault for contributing!

you're welcome. For your information, I'm using sse2neon to provide a much faster implementation of std::min_element / max_element for primitive types in https://github.com/OSGeo/gdal/pull/11202

**Pull request merged**
