### PR TITLE
refactor: Replace conditional op with binary operation

### PR DESCRIPTION
**Pull request by HowJMay**
Some conditional operations can be replaced with binary operations
which should be able to accelerate the functions by removing branch
prediction.

### CODE REVIEW

**Review by marktwtn — CHANGES_REQUESTED** [review]
Revise the commit message:
`accelerate the functions with better branch prediction.`
-> `accelerate the functions by removing branch prediction.`

I think `!!` is hard to read.
Use `& 0x1` may be a good way to implement.

**Comment by HowJMay** [comment]
> Revise the commit message:
> `accelerate the functions with better branch prediction.`
> -> `accelerate the functions by removing branch prediction.`
> 
> I think `!!` is hard to read.
> Use `& 0x1` may be a good way to implement.

you mean change to this way ?
`return !vgetq_lane_u32(vorrq_u32(a_or_b_nan, a_neq_b), 0) & 0x1;`

**Comment by marktwtn** [comment]
> > Revise the commit message:
> > `accelerate the functions with better branch prediction.`
> > -> `accelerate the functions by removing branch prediction.`
> > I think `!!` is hard to read.
> > Use `& 0x1` may be a good way to implement.
> 
> you mean change to this way ?
> `return !vgetq_lane_u32(vorrq_u32(a_or_b_nan, a_neq_b), 0) & 0x1;`
> 
> If so, I prefer `!!` tho

For example:
`!!vgetq_lane_u32(vandq_u32(a_and_b_not_nan, a_eq_b), 0)` would be
`vgetq_lane_u32(vandq_u32(a_and_b_not_nan, a_eq_b), 0) & 0x1`.

**Comment by HowJMay** [comment]
> > > Revise the commit message:
> > > `accelerate the functions with better branch prediction.`
> > > -> `accelerate the functions by removing branch prediction.`
> > > I think `!!` is hard to read.
> > > Use `& 0x1` may be a good way to implement.
> > 
> > 
> > you mean change to this way ?
> > `return !vgetq_lane_u32(vorrq_u32(a_or_b_nan, a_neq_b), 0) & 0x1;`
> > If so, I prefer `!!` tho
> 
> For example:
> `!!vgetq_lane_u32(vandq_u32(a_and_b_not_nan, a_eq_b), 0)` would be
> `vgetq_lane_u32(vandq_u32(a_and_b_not_nan, a_eq_b), 0) & 0x1`.

Maybe I miscalculate something here, but I think `!!vgetq_lane_u32(vandq_u32(a_and_b_not_nan, a_eq_b), 0)` is not equal to `vgetq_lane_u32(vandq_u32(a_and_b_not_nan, a_eq_b), 0) & 0x1`.

I think we are not able to ensure a non-zero number with 1 in the least significant bit

**Comment by marktwtn** [comment]
> Maybe I miscalculate something here, but I think `!!vgetq_lane_u32(vandq_u32(a_and_b_not_nan, a_eq_b), 0)` is not equal to `vgetq_lane_u32(vandq_u32(a_and_b_not_nan, a_eq_b), 0) & 0x1`.
> 
> I think we are not able to ensure a non-zero number with 1 in the least significant bit

However, the intrinsics before the return value are mostly composed with comparison intrinsics.
Therefore, the non-zero value would be `0xFFFFFFFF`.

**Comment by HowJMay** [comment]
> > Maybe I miscalculate something here, but I think `!!vgetq_lane_u32(vandq_u32(a_and_b_not_nan, a_eq_b), 0)` is not equal to `vgetq_lane_u32(vandq_u32(a_and_b_not_nan, a_eq_b), 0) & 0x1`.
> > I think we are not able to ensure a non-zero number with 1 in the least significant bit
> 
> However, the intrinsics before the return value are mostly composed with comparison intrinsics.
> Therefore, the non-zero value would be `0xFFFFFFFF`.

Got it. It is my fault. But I still prefer `!!`. Could we let @jserv decide which way we should choose?

**Comment by marktwtn** [comment]
> Got it. It is my fault. But I still prefer `!!`. Could we let @jserv decide which way we should choose?

There is another opinion I would like to share that I think `!!` would have two logic operationw and `& 0x1` would only have one logic operation.

**Comment by HowJMay** [comment]
> > Got it. It is my fault. But I still prefer `!!`. Could we let @jserv decide which way we should choose?
> 
> There is another opinion I would like to share that I think `!!` would have two logic operationw and `& 0x1` would only have one logic operation.

That is a good point. I will change it

**Review by marktwtn — APPROVED** [review]

**Pull request merged**
