### PR TITLE
Add _mm_getcsr and rounding defines

### PR DESCRIPTION
**Pull request by nlacey**
Add _mm_getcsr and rounding defines

### CODE REVIEW

**Comment by jserv** [comment]
Please manage to implement the corresponding test item for `_mm_getscr`.

**Comment by nlacey** [comment]
I'm a little confused with the unit tests running on x86?
when I try and run on my x86-64 (on master branch) I get 
tests/impl.cpp:2023:19: error: ‘_mm_loadu_si64’ was not declared in this scope.

**Comment by marktwtn** [comment]
The commit header should be `_mm_getcsr` not `_mm_getscr`.

**Comment by nlacey** [comment]
I saved off the original csr value and restored the original csr value after the unit test was done so I shouldn't modify the running of other tests now.

**Comment by marktwtn** [comment]
@nlacey use `$ make indent` to fix the coding style, and please rebase the commits to a single one.

**Pull request merged**
