### PR TITLE
feat: Add intrinsics _mm_xor_si64

### PR DESCRIPTION
**Pull request by HowJMay**

### CODE REVIEW

**Comment by jserv** [comment]
`_mm_xor_si641` is part of MMX instead of SSE family. I hesitated to pick this up.

**Comment by marktwtn** [comment]
> 
> 
> `_mm_xor_si641` is part of MMX instead of SSE family. I hesitated to pick this up.

Agree.

**Comment by HowJMay** [comment]
Do we need to remove the description about MMX here?
https://github.com/DLTcollab/sse2neon#mapping-and-coverage

**Comment by jserv** [comment]
> Do we need to remove the description about MMX here?
> https://github.com/DLTcollab/sse2neon#mapping-and-coverage

The current statement is "sse2neon aims to support SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2 and AES extension."

**Comment by HowJMay** [comment]
> > Do we need to remove the description about MMX here?
> > https://github.com/DLTcollab/sse2neon#mapping-and-coverage
> 
> The current statement is "sse2neon aims to support SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2 and AES extension."

I mean the table above mentioning MMX. Should we remove it?

**Comment by jserv** [comment]
> I mean the table above mentioning MMX. Should we remove it?

The table can be left for reference purpose.

**Comment by HowJMay** [comment]
> > I mean the table above mentioning MMX. Should we remove it?
> 
> The table can be left for reference purpose.

OK let me close this PR

**Pull request closed without merging**
