### PR TITLE
refactor: Classify intrinsic functions

### PR DESCRIPTION
**Pull request by marktwtn**
The classification can help the developer find the unimplemented
intrinsic functions quickly.
The classification is referenced from:
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#

### CODE REVIEW

**Comment by marktwtn** [comment]
> Inconsistent style

It is weird that I do not modify the code which causes the inconsistent style.
And it is not detected in the previous commits.

**Comment by marktwtn** [comment]
@jserv it has a weird coding style checking like this:

sse2neon.h
```
-    // AES
+// AES
 #if !defined(__arm__) && __ARM_ARCH != 7
     IT_MM_AESENC_SI128,
 #endif
```

**Comment by marktwtn** [comment]
> clang-format in script ".ci/check-format.sh" should be replaced with "clang-format-6"

I am pretty sure that it would use `clang-format-6` in Travis CI without changing the script.
I'm afraid that the weird coding style checking is caused by `clang-format-6` and `.clang-format`.

**Comment by jserv** [comment]
> it has a weird coding style checking like this:
> ```
> -    // AES
> +// AES
>  #if !defined(__arm__) && __ARM_ARCH != 7
>      IT_MM_AESENC_SI128,
>  #endif
> ```

I don't think it is a problem after #63 is merged.

**Pull request merged**
