### PR TITLE
fix: Fix MSVC error in CI

### PR DESCRIPTION
**Pull request by howjmay**

### CODE REVIEW

**Comment by howjmay** [comment]
Hi @anthony-linaro CI for windows host failed for unknown reason. 
I have checked out the `sse2neon.exe` exists and `wine-arm64 --version` can work.
Do you have idea how to solve it?

**Comment by anthony-linaro** [comment]
Hi @howjmay - I have poked the person on my team who published the wine container, @pbo-linaro - hopefully he can weigh in

**Comment by pbo-linaro** [comment]
Hi @howjmay, I just noticed this regression this morning. It's related to update of QEMU used to run wine in our container ([details here](https://gitlab.com/Linaro/windowsonarm/woa-linux/-/commit/c8dc5395befd2d3304aff3bf43da98014e085495)).

 It's specific to Github Actions (it works on raw machine, or on Gitlab CI) . I'm looking at it now, and if no solution is found, I'll revert back this change, so fixed image will be pushed before end of the day.

Sorry for the inconvenience.

**Comment by howjmay** [comment]
@pbo-linaro @anthony-linaro Thank you for your help!

**Comment by pbo-linaro** [comment]
`linaro/wine-arm64:latest` image is now fixed. Other versions are being built.

**Comment by jserv** [comment]
Thank @pbo-linaro and @anthony-linaro for supporting!

**Pull request closed without merging**
