### PR TITLE
_mm_sad_epu8(): use only Neon intrinsics instead of scalar operations

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Review by HowJMay — APPROVED** [review]
It dramatically reduce the number of instructions

original:
https://godbolt.org/z/5oYxoeYdq

modified:
https://godbolt.org/z/aK71fWaYz

**Review by marktwtn — APPROVED** [review]

**Comment by rouault** [comment]
to be more realistic, you should build with -02. So original (https://godbolt.org/z/ojW16M3zE) vs modified (https://godbolt.org/z/Mcz4drhEh)

**Comment by marktwtn** [comment]
@rouault thank you for your contribution.

**Comment by HowJMay** [comment]
@rouault Thank you for your contribution and advice

**Pull request merged**
